In [82]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [83]:
X,y = load_iris(return_X_y=True)

In [84]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [85]:
X_train , X_test , y_train, y_test = train_test_split(X,y , test_size = 0.2)

## You can compare the X before and After Preprocessing

In [86]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [87]:
X_train_scaled

array([[-0.77827642, -0.85994275,  0.11813105,  0.31375753],
       [ 1.03635773,  0.04526014,  0.56461061,  0.44494535],
       [ 0.55245529, -0.63364203,  0.78785039,  0.44494535],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.36326007],
       [-1.50413008,  0.72416232, -1.27711758, -1.12930846],
       [-0.77827642,  2.30826739, -1.22130763, -1.3916841 ],
       [ 1.76221139, -0.4073413 ,  1.45756974,  0.8385088 ],
       [ 0.6734309 , -0.85994275,  0.89947028,  0.96969662],
       [-1.02022764,  0.27156087, -1.38873747, -1.26049628],
       [ 1.15733334, -0.63364203,  0.62042056,  0.31375753],
       [ 0.31050407, -0.18104058,  0.50880067,  0.31375753],
       [-0.17339837, -0.18104058,  0.28556089,  0.0513819 ],
       [ 0.18952846, -0.85994275,  0.78785039,  0.57613316],
       [-1.86705691, -0.18104058, -1.44454742, -1.3916841 ],
       [-0.5363252 ,  1.85566594, -1.33292752, -0.99812064],
       [ 0.55245529, -0.85994275,  0.6762305 ,  0.8385088 ],
       [-1.50413008,  1.17676377, -1.50035736, -1.26049628],
       [ 0.6734309 ,  0.04526014,  1.01109017,  0.8385088 ],
       [ 0.18952846, -0.4073413 ,  0.45299072,  0.44494535],
       [-0.77827642,  0.95046304, -1.22130763, -1.26049628],
       [-0.89925203,  0.95046304, -1.27711758, -1.12930846],
       [ 0.18952846, -1.99144637,  0.173941  , -0.21099374],
       [ 2.48806505,  1.62936521,  1.51337968,  1.10088443],
       [ 1.03635773, -1.3125442 ,  1.17852001,  0.8385088 ],
       [-1.14120325,  1.17676377, -1.27711758, -1.3916841 ],
       [ 0.43147968, -0.63364203,  0.62042056,  0.8385088 ],
       [ 1.15733334, -0.18104058,  1.01109017,  1.23207225],
       [ 0.31050407, -0.4073413 ,  0.56461061,  0.31375753],
       [-1.26217886, -0.18104058, -1.27711758, -1.12930846],
       [ 1.27830895,  0.04526014,  0.95528023,  1.23207225],
       [-0.29437398, -0.18104058,  0.22975094,  0.18256971],
       [-0.5363252 ,  0.72416232, -1.10968774, -1.26049628],
       [-1.50413008,  0.04526014, -1.22130763, -1.26049628],
       [-0.89925203,  1.62936521, -1.16549769, -1.26049628],
       [-1.7460813 , -0.4073413 , -1.27711758, -1.26049628],
       [-0.17339837, -1.3125442 ,  0.73204045,  1.10088443],
       [ 0.79440651, -0.18104058,  1.01109017,  0.8385088 ],
       [ 1.03635773,  0.04526014,  0.39718078,  0.31375753],
       [-1.14120325, -1.3125442 ,  0.45299072,  0.70732098],
       [-0.05242276, -0.85994275,  0.11813105,  0.0513819 ],
       [-0.29437398, -1.3125442 ,  0.11813105, -0.07980592],
       [-0.41534959, -1.76514565,  0.173941  ,  0.18256971],
       [ 0.18952846,  0.72416232,  0.45299072,  0.57613316],
       [-0.41534959, -1.08624348,  0.39718078,  0.0513819 ],
       [-0.17339837,  2.98716956, -1.22130763, -0.99812064],
       [ 0.55245529,  0.72416232,  1.06690012,  1.6256357 ],
       [-1.02022764,  0.72416232, -1.22130763, -1.26049628],
       [-1.02022764, -0.18104058, -1.16549769, -1.26049628],
       [ 0.79440651, -0.18104058,  0.84366034,  1.10088443],
       [ 0.55245529,  0.49786159,  1.2901399 ,  1.75682352],
       [ 2.24611383, -0.63364203,  1.68080952,  1.10088443],
       [-0.89925203,  0.49786159, -1.10968774, -0.86693283],
       [-0.17339837, -0.63364203,  0.22975094,  0.18256971],
       [-0.05242276, -0.85994275,  0.22975094, -0.21099374],
       [-1.38315447,  0.27156087, -1.16549769, -1.26049628],
       [-1.26217886,  0.04526014, -1.16549769, -1.26049628],
       [-0.5363252 ,  1.85566594, -1.10968774, -0.99812064],
       [-1.38315447,  0.27156087, -1.33292752, -1.26049628],
       [ 2.24611383,  1.62936521,  1.68080952,  1.36326007],
       [ 0.43147968,  0.72416232,  0.95528023,  1.49444789],
       [ 0.6734309 , -0.4073413 ,  0.34137083,  0.18256971],
       [ 1.03635773,  0.04526014,  1.06690012,  1.6256357 ],
       [ 0.6734309 ,  0.27156087,  0.45299072,  0.44494535],
       [ 0.18952846, -0.18104058,  0.62042056,  0.8385088 ],
       [ 2.24611383, -1.08624348,  1.79242941,  1.49444789],
       [-1.02022764,  0.95046304, -1.33292752, -1.12930846],
       [-0.05242276, -0.85994275,  0.78785039,  0.96969662],
       [-1.26217886,  0.72416232, -0.99806785, -1.26049628],
       [ 1.883187  , -0.63364203,  1.34594985,  0.96969662],
       [ 0.91538212, -0.18104058,  0.39718078,  0.31375753],
       [-1.7460813 , -0.18104058, -1.33292752, -1.26049628],
       [ 0.43147968, -1.99144637,  0.45299072,  0.44494535],
       [-0.89925203,  1.62936521, -1.22130763, -1.12930846],
       [-0.05242276, -1.08624348,  0.173941  ,  0.0513819 ],
       [ 2.24611383, -0.18104058,  1.34594985,  1.49444789],
       [-1.26217886, -0.18104058, -1.27711758, -1.3916841 ],
       [-0.41534959, -1.53884492,  0.00651116, -0.21099374],
       [ 1.03635773,  0.49786159,  1.12271006,  1.75682352],
       [-0.29437398, -0.4073413 , -0.04929878,  0.18256971],
       [-1.02022764,  0.72416232, -1.16549769, -0.99812064],
       [ 1.64123578, -0.18104058,  1.17852001,  0.57613316],
       [ 0.31050407, -0.63364203,  0.173941  ,  0.18256971],
       [-0.77827642,  0.72416232, -1.27711758, -1.26049628],
       [-0.29437398, -0.85994275,  0.28556089,  0.18256971],
       [ 1.64123578,  0.27156087,  1.2901399 ,  0.8385088 ],
       [-0.89925203,  0.95046304, -1.27711758, -1.26049628],
       [-0.17339837,  1.62936521, -1.10968774, -1.12930846],
       [-1.02022764,  0.49786159, -1.27711758, -1.26049628],
       [-0.41534959, -1.3125442 ,  0.173941  ,  0.18256971],
       [-1.7460813 ,  0.27156087, -1.33292752, -1.26049628],
       [ 0.18952846, -1.99144637,  0.73204045,  0.44494535],
       [ 0.31050407, -0.18104058,  0.6762305 ,  0.8385088 ],
       [ 1.27830895,  0.04526014,  0.78785039,  1.49444789],
       [ 0.06855285, -0.18104058,  0.78785039,  0.8385088 ],
       [ 0.79440651, -0.63364203,  0.50880067,  0.44494535],
       [-0.05242276, -0.85994275,  0.78785039,  0.96969662],
       [-1.02022764,  0.95046304, -1.16549769, -0.73574501],
       [ 0.31050407, -1.08624348,  1.06690012,  0.31375753],
       [-0.41534959,  0.95046304, -1.33292752, -1.26049628],
       [-0.65730081,  1.40306449, -1.22130763, -1.26049628],
       [ 0.55245529, -1.3125442 ,  0.73204045,  0.96969662],
       [ 0.55245529,  0.49786159,  0.56461061,  0.57613316],
       [ 1.27830895,  0.04526014,  0.6762305 ,  0.44494535],
       [-1.02022764, -2.44404782, -0.10510873, -0.21099374],
       [-0.5363252 ,  0.72416232, -1.22130763, -0.99812064],
       [-0.41534959, -1.53884492,  0.06232111, -0.07980592],
       [ 0.79440651, -0.18104058,  1.17852001,  1.36326007],
       [ 1.39928456,  0.27156087,  0.56461061,  0.31375753],
       [-0.05242276,  2.08196666, -1.38873747, -1.26049628],
       [-0.17339837, -1.08624348, -0.10510873, -0.21099374],
       [ 1.15733334,  0.27156087,  1.23432996,  1.49444789],
       [ 1.27830895,  0.27156087,  1.12271006,  1.49444789],
       [-1.26217886,  0.72416232, -1.16549769, -1.26049628],
       [-1.14120325, -0.18104058, -1.27711758, -1.26049628],
       [ 0.43147968, -0.4073413 ,  0.34137083,  0.18256971],
       [-0.89925203,  0.72416232, -1.22130763, -1.26049628],
       [-0.5363252 ,  1.40306449, -1.22130763, -1.26049628],
       [ 0.06855285,  0.27156087,  0.62042056,  0.8385088 ],
       [-0.41534959,  2.53456811, -1.27711758, -1.26049628],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.23207225]])

## Behind the logic of StandardScaler

In [88]:
import numpy as np

(X_train - np.mean(X_train, axis =0)) / np.std(X_train, axis=0)

array([[-0.77827642, -0.85994275,  0.11813105,  0.31375753],
       [ 1.03635773,  0.04526014,  0.56461061,  0.44494535],
       [ 0.55245529, -0.63364203,  0.78785039,  0.44494535],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.36326007],
       [-1.50413008,  0.72416232, -1.27711758, -1.12930846],
       [-0.77827642,  2.30826739, -1.22130763, -1.3916841 ],
       [ 1.76221139, -0.4073413 ,  1.45756974,  0.8385088 ],
       [ 0.6734309 , -0.85994275,  0.89947028,  0.96969662],
       [-1.02022764,  0.27156087, -1.38873747, -1.26049628],
       [ 1.15733334, -0.63364203,  0.62042056,  0.31375753],
       [ 0.31050407, -0.18104058,  0.50880067,  0.31375753],
       [-0.17339837, -0.18104058,  0.28556089,  0.0513819 ],
       [ 0.18952846, -0.85994275,  0.78785039,  0.57613316],
       [-1.86705691, -0.18104058, -1.44454742, -1.3916841 ],
       [-0.5363252 ,  1.85566594, -1.33292752, -0.99812064],
       [ 0.55245529, -0.85994275,  0.6762305 ,  0.8385088 ],
       [-1.50413008,  1.17676377, -1.50035736, -1.26049628],
       [ 0.6734309 ,  0.04526014,  1.01109017,  0.8385088 ],
       [ 0.18952846, -0.4073413 ,  0.45299072,  0.44494535],
       [-0.77827642,  0.95046304, -1.22130763, -1.26049628],
       [-0.89925203,  0.95046304, -1.27711758, -1.12930846],
       [ 0.18952846, -1.99144637,  0.173941  , -0.21099374],
       [ 2.48806505,  1.62936521,  1.51337968,  1.10088443],
       [ 1.03635773, -1.3125442 ,  1.17852001,  0.8385088 ],
       [-1.14120325,  1.17676377, -1.27711758, -1.3916841 ],
       [ 0.43147968, -0.63364203,  0.62042056,  0.8385088 ],
       [ 1.15733334, -0.18104058,  1.01109017,  1.23207225],
       [ 0.31050407, -0.4073413 ,  0.56461061,  0.31375753],
       [-1.26217886, -0.18104058, -1.27711758, -1.12930846],
       [ 1.27830895,  0.04526014,  0.95528023,  1.23207225],
       [-0.29437398, -0.18104058,  0.22975094,  0.18256971],
       [-0.5363252 ,  0.72416232, -1.10968774, -1.26049628],
       [-1.50413008,  0.04526014, -1.22130763, -1.26049628],
       [-0.89925203,  1.62936521, -1.16549769, -1.26049628],
       [-1.7460813 , -0.4073413 , -1.27711758, -1.26049628],
       [-0.17339837, -1.3125442 ,  0.73204045,  1.10088443],
       [ 0.79440651, -0.18104058,  1.01109017,  0.8385088 ],
       [ 1.03635773,  0.04526014,  0.39718078,  0.31375753],
       [-1.14120325, -1.3125442 ,  0.45299072,  0.70732098],
       [-0.05242276, -0.85994275,  0.11813105,  0.0513819 ],
       [-0.29437398, -1.3125442 ,  0.11813105, -0.07980592],
       [-0.41534959, -1.76514565,  0.173941  ,  0.18256971],
       [ 0.18952846,  0.72416232,  0.45299072,  0.57613316],
       [-0.41534959, -1.08624348,  0.39718078,  0.0513819 ],
       [-0.17339837,  2.98716956, -1.22130763, -0.99812064],
       [ 0.55245529,  0.72416232,  1.06690012,  1.6256357 ],
       [-1.02022764,  0.72416232, -1.22130763, -1.26049628],
       [-1.02022764, -0.18104058, -1.16549769, -1.26049628],
       [ 0.79440651, -0.18104058,  0.84366034,  1.10088443],
       [ 0.55245529,  0.49786159,  1.2901399 ,  1.75682352],
       [ 2.24611383, -0.63364203,  1.68080952,  1.10088443],
       [-0.89925203,  0.49786159, -1.10968774, -0.86693283],
       [-0.17339837, -0.63364203,  0.22975094,  0.18256971],
       [-0.05242276, -0.85994275,  0.22975094, -0.21099374],
       [-1.38315447,  0.27156087, -1.16549769, -1.26049628],
       [-1.26217886,  0.04526014, -1.16549769, -1.26049628],
       [-0.5363252 ,  1.85566594, -1.10968774, -0.99812064],
       [-1.38315447,  0.27156087, -1.33292752, -1.26049628],
       [ 2.24611383,  1.62936521,  1.68080952,  1.36326007],
       [ 0.43147968,  0.72416232,  0.95528023,  1.49444789],
       [ 0.6734309 , -0.4073413 ,  0.34137083,  0.18256971],
       [ 1.03635773,  0.04526014,  1.06690012,  1.6256357 ],
       [ 0.6734309 ,  0.27156087,  0.45299072,  0.44494535],
       [ 0.18952846, -0.18104058,  0.62042056,  0.8385088 ],
       [ 2.24611383, -1.08624348,  1.79242941,  1.49444789],
       [-1.02022764,  0.95046304, -1.33292752, -1.12930846],
       [-0.05242276, -0.85994275,  0.78785039,  0.96969662],
       [-1.26217886,  0.72416232, -0.99806785, -1.26049628],
       [ 1.883187  , -0.63364203,  1.34594985,  0.96969662],
       [ 0.91538212, -0.18104058,  0.39718078,  0.31375753],
       [-1.7460813 , -0.18104058, -1.33292752, -1.26049628],
       [ 0.43147968, -1.99144637,  0.45299072,  0.44494535],
       [-0.89925203,  1.62936521, -1.22130763, -1.12930846],
       [-0.05242276, -1.08624348,  0.173941  ,  0.0513819 ],
       [ 2.24611383, -0.18104058,  1.34594985,  1.49444789],
       [-1.26217886, -0.18104058, -1.27711758, -1.3916841 ],
       [-0.41534959, -1.53884492,  0.00651116, -0.21099374],
       [ 1.03635773,  0.49786159,  1.12271006,  1.75682352],
       [-0.29437398, -0.4073413 , -0.04929878,  0.18256971],
       [-1.02022764,  0.72416232, -1.16549769, -0.99812064],
       [ 1.64123578, -0.18104058,  1.17852001,  0.57613316],
       [ 0.31050407, -0.63364203,  0.173941  ,  0.18256971],
       [-0.77827642,  0.72416232, -1.27711758, -1.26049628],
       [-0.29437398, -0.85994275,  0.28556089,  0.18256971],
       [ 1.64123578,  0.27156087,  1.2901399 ,  0.8385088 ],
       [-0.89925203,  0.95046304, -1.27711758, -1.26049628],
       [-0.17339837,  1.62936521, -1.10968774, -1.12930846],
       [-1.02022764,  0.49786159, -1.27711758, -1.26049628],
       [-0.41534959, -1.3125442 ,  0.173941  ,  0.18256971],
       [-1.7460813 ,  0.27156087, -1.33292752, -1.26049628],
       [ 0.18952846, -1.99144637,  0.73204045,  0.44494535],
       [ 0.31050407, -0.18104058,  0.6762305 ,  0.8385088 ],
       [ 1.27830895,  0.04526014,  0.78785039,  1.49444789],
       [ 0.06855285, -0.18104058,  0.78785039,  0.8385088 ],
       [ 0.79440651, -0.63364203,  0.50880067,  0.44494535],
       [-0.05242276, -0.85994275,  0.78785039,  0.96969662],
       [-1.02022764,  0.95046304, -1.16549769, -0.73574501],
       [ 0.31050407, -1.08624348,  1.06690012,  0.31375753],
       [-0.41534959,  0.95046304, -1.33292752, -1.26049628],
       [-0.65730081,  1.40306449, -1.22130763, -1.26049628],
       [ 0.55245529, -1.3125442 ,  0.73204045,  0.96969662],
       [ 0.55245529,  0.49786159,  0.56461061,  0.57613316],
       [ 1.27830895,  0.04526014,  0.6762305 ,  0.44494535],
       [-1.02022764, -2.44404782, -0.10510873, -0.21099374],
       [-0.5363252 ,  0.72416232, -1.22130763, -0.99812064],
       [-0.41534959, -1.53884492,  0.06232111, -0.07980592],
       [ 0.79440651, -0.18104058,  1.17852001,  1.36326007],
       [ 1.39928456,  0.27156087,  0.56461061,  0.31375753],
       [-0.05242276,  2.08196666, -1.38873747, -1.26049628],
       [-0.17339837, -1.08624348, -0.10510873, -0.21099374],
       [ 1.15733334,  0.27156087,  1.23432996,  1.49444789],
       [ 1.27830895,  0.27156087,  1.12271006,  1.49444789],
       [-1.26217886,  0.72416232, -1.16549769, -1.26049628],
       [-1.14120325, -0.18104058, -1.27711758, -1.26049628],
       [ 0.43147968, -0.4073413 ,  0.34137083,  0.18256971],
       [-0.89925203,  0.72416232, -1.22130763, -1.26049628],
       [-0.5363252 ,  1.40306449, -1.22130763, -1.26049628],
       [ 0.06855285,  0.27156087,  0.62042056,  0.8385088 ],
       [-0.41534959,  2.53456811, -1.27711758, -1.26049628],
       [ 0.6734309 , -0.63364203,  1.06690012,  1.23207225]])

- what we are doing with StandardScaler is avobe with numpy both outputs are same

# Min-Max Scaling

In [89]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.transform(X_test)

In [90]:
X_train_Scaled

array([[0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.58333333, 0.33333333, 0.77966102, 0.83333333]])

# Encoding Data Very Important

## OrdinalEncoder

In [91]:
# We use an Encoder to Convert Data from Text to numbers bcz Algorithms work on Numbers not on characters

from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [92]:
data = fetch_openml('car',as_frame=True).frame

/Users/macbookair/Python/sk_learn/env/lib/python3.11/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [93]:
data

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

- here we can see that safety amd lug_boot columns are not in numerical form to perform ML
- so we will convert this to numeric

## *How do we know on which columns we have to apply encoder or not?*

-  your data should we be in Order for example there is an order in education that fist there is primary educatioin then scendoray and so on same in these columns there is an order small med high low mid high so we use *OrdinalEncoder* here

- for other columns like countries where there is no oder u cannot classify those columns on the bases of order or rank u use another encoder which is called *OneHotEncoder*

In [94]:
columns_to_encode = ['lug_boot','safety']

encoder = OrdinalEncoder(
    categories = [
        ['small','med','big'],
        ['low', 'med','high']
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [95]:
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

- now u can see numbers in lug_boot and in safety columns

### We can also inverse the transform

In [96]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

# OneHotEncoder

In [97]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [98]:
data = fetch_openml('adult',as_frame=True).frame

/Users/macbookair/Python/sk_learn/env/lib/python3.11/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

In [99]:
data

      age         workclass  fnlwgt  ... hoursperweek  native-country  class
0       2         State-gov   77516  ...            2   United-States  <=50K
1       3  Self-emp-not-inc   83311  ...            0   United-States  <=50K
2       2           Private  215646  ...            2   United-States  <=50K
3       3           Private  234721  ...            2   United-States  <=50K
4       1           Private  338409  ...            2            Cuba  <=50K
...    ..               ...     ...  ...          ...             ...    ...
48837   2           Private  215419  ...            2   United-States  <=50K
48838   4               NaN  321403  ...            2   United-States  <=50K
48839   2           Private  374983  ...            3   United-States  <=50K
48840   2           Private   83891  ...            2   United-States  <=50K
48841   1      Self-emp-inc  182148  ...            3   United-States   >50K

[48842 rows x 15 columns]

In [100]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [101]:
encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

encoded_values = encoder.fit_transform(data[['occupation','race']])
new_cols = encoder.get_feature_names_out(['occupation','race'])

In [102]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [103]:
df_encoded = pd.DataFrame(encoded_values , columns = new_cols, index =data.index)
data_final = pd.concat(
    [data.drop(columns=['occupation','race']),df_encoded],
    axis=1
)

In [104]:
data_final

      age         workclass  fnlwgt  ... race_Black  race_Other race_White
0       2         State-gov   77516  ...        0.0         0.0        1.0
1       3  Self-emp-not-inc   83311  ...        0.0         0.0        1.0
2       2           Private  215646  ...        0.0         0.0        1.0
3       3           Private  234721  ...        1.0         0.0        0.0
4       1           Private  338409  ...        1.0         0.0        0.0
...    ..               ...     ...  ...        ...         ...        ...
48837   2           Private  215419  ...        0.0         0.0        1.0
48838   4               NaN  321403  ...        1.0         0.0        0.0
48839   2           Private  374983  ...        0.0         0.0        1.0
48840   2           Private   83891  ...        0.0         0.0        0.0
48841   1      Self-emp-inc  182148  ...        0.0         0.0        1.0

[48842 rows x 33 columns]